version: '3.8'

services:
  loadbalancer_front:
    image: lucaslrodrigues/loadbalancer_front:0.1
    ports:
      - "80:80"
    env_file:
      - ./.env
    networks:
      - lb_network

networks:
  lb_network:
